config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :likes, only: [:index, :create]
  devise_for :users, controllers: {registrations: "registrations"}

  post 'answers' => 'questions#create_answer'
  get 'hot_questions' => 'questions#rated'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'questions#index'
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  response    :text
#  likes       :integer          default(0)
#  confirmed   :boolean
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates_presence_of :response
  belongs_to :question
  belongs_to :user
  has_many :votes, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates_presence_of :title, :body
  has_many :answers, dependent: :destroy
  belongs_to :user

  scope :hot_likes, -> {joins(:answers).where('answers.likes > ?', 0 ).order('likes DESC')}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  answer_id  :integer
#

class Vote < ApplicationRecord
  belongs_to :answer
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @answer = Answer.find(params['data'])
    @query = Question.find(@answer.question_id)
    @vote = Vote.where(answer_id: @answer.id, user_id: current_user.id).take
    if @vote == nil
      @vote = Vote.new(user: current_user, answer: @answer)
        if @query.user == current_user
          @answer.confirmed = true
        end
      @vote.save
      @answer.likes +=1
      @answer.save
    else
      @answer.likes -=1
      @answer.save
      @vote.destroy
    end
  redirect_to question_path(@query.id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @question = Question.new
    @questions = Question.all.reverse_order.page(params[:page]).per(10)
    # @questions = Question.hot_likes.page(params[:page]).per(10)
  end

  def create
    @question = Question.new(params.require(:question).permit(:title, :body))
    @question.user = current_user
    @question.image = params[:question][:image]
    if @question.save
    else
      flash[:error] = 'This fields are required'
    end
    redirect_to action: 'index'
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    if cookies[:alert].present?
      cookies[:alert] = cookies[:alert].to_i + 1
    else
      cookies[:alert] = 1
    end

  end

  def destroy
    @question = Question.find(params[:id])
    if @question.user == current_user
      @question.destroy
    else
      flash[:error] = 'You must be the owner'
    end
    redirect_to action: 'index'
  end

  def create_answer
    @answer = Answer.new(params.require(:answer).permit(:response, :question_id))
    @answer.user = current_user
    @answer.question_id=params[:question_id]
    @answer.image = params[:answer][:image]
    if @answer.save
    else
      flash[:error] = 'This field is required'
    end
    redirect_to question_path(params[:question_id])
  end

  def rated
    @questions = Question.hot_likes.page(params[:page]).per(10)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <title>SwapOwerflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">SwapOwerflow</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li class="active"><%= link_to "HOT", hot_questions_path, :method => 'get' %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' if current_user%></li>
        <li><%= link_to "Login", new_user_session_path, :method => 'get' if not current_user %></li>
      </ul>
    </div>
  </nav>
  <%= image_tag('swap.png', class:"logo")%>
  <div class="container">
    <% flash.each do |key, value| %>
        <li class="list-group-item list-group-item-info"><%= value %></li>
    <% end %>
  </div>
  <% if user_signed_in? %>
      <h5>Welcome, <%=current_user.name %></h5>
  <% end %>
  <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <ul class="list-group">
      <div class="span4">
        <div class="form">
          <%= form_for @question do |f| %>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls">
                  <p><%= f.text_field :title, class: "form-control", placeholder:"Theme of question" %></p>
                </div>
              </div>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls">
                  <p><%= f.text_area :body,  class: "form-control", placeholder:"Question" %></p>
                </div>
                <div class="form-group floating-label-form-group controls">
                  <p><%= f.file_field :image %></p>
                </div>
              </div>
              <p><%= f.submit class: "btn btn-success btn-sm"%></p>
              </div>
      </div>
        <% end %>
        </ul>
  </div>
  <ul>
    <div class="notice">
      <%= flash.notice%>
    </div>
    <% @questions.each.with_index(1) do |question, index| %>
        <li class="list-group-item ">#<%= index %>
          <%= link_to question.title, question_path(id: question.id) %></li>
          <li class="list-group-item list-group-item-success"><%= truncate(question.body) { link_to "More", question_path(id: question.id) } %></li>
        <span><i>Posted by: <b><%= question.user.name %></b> at <%= question.created_at.to_formatted_s(:short) %></i></span>
        <hr>
  <% end %>
  </ul>
  <%= paginate @questions %>
  </div>

</div>

app/views/questions/rated.html.erb
<div class="row">
  <ul>
    <% for question in @questions %>
        <li class="list-group-item list-group-item-success">
          <%= link_to question.title, question_path(id: question.id) %>
        </li>
        <span><i>Posted by: <b><%= question.user.name %></b></i></span>
        <hr>

    <% end %>
  </ul>
</div>

app/views/questions/show.html.erb
<div class="container">

  <div class="span3">
    <% if cookies[:alert] > 3 and not current_user %>
      <script>
        alert("Please login to have more fun!=)")
      </script>
        <% end %>
      <li class="list-group-item active"><%= @question.title %> <%=link_to image_tag("del.png", class: "like"), question_path(id: @question.id), method: :delete %></li>
      <li class="list-group-item list-group-item-success"><%= @question.body %></li>
      <p><%=link_to image_tag(@question.image_url, class: 'thumb'), @question.image_url, target: "_blank" if @question.image? %></p>
      <span><i>Question by: </i><%= @question.user.name %></span>
      <ul class="list-group">
        <% @question.answers.each do |answer| %>
            <li class="list-group-item active"><%= answer.response %></li>
            <p><%=link_to image_tag(answer.image_url, class: 'thumb'), answer.image_url, target: "_blank" if answer.image? %></p>
            <span><i>Posted by: </i><%= answer.user.name%></span>
            <%= link_to image_tag("like.jpg", class:"like"), likes_path(data: answer.id), method: :post %>:<%=answer.likes%>
            <% if answer.confirmed%>
                <%= image_tag("cake.jpg", class:"like") %>
            <% end %>
            <% end %>
      </ul>
      <div class="form">
        <div class="row">
          <%= form_for @answer do |f| %>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls">
                  <p><%= f.text_area :response, class:"form-control", placeholder:"I think ..." %></p>
                </div>
                <div class="form-group floating-label-form-group controls">
                  <p><%= f.file_field :image %></p>
                </div>
              </div>
              <input type="hidden" name="question_id" value="<%= @question.id %>">
              <p><%= f.submit "Answer", class:"btn btn-success btn-sm" %></p>
          <% end %>
        </div>
      </div>
      </div>
    </div>